# Introduction to Keras and TensorFlow

## 3.1 What's TensorFlow?

## 3.2 What's Keras?

## 3.3 Keras and TensorFlow: A brief history

## 3.4 Setting up a deep learning workspace

### 3.4.1 Jupyter notebooks: The preferred way to run deep learning experiments

### 3.4.2 Using Colaboratory

## 3.5 First steps with TensorFlow

### 3.5.1 Constant tensors and variables

**All-ones or all-zeros tensors**

In [2]:
import tensorflow as tf
x = tf.ones(shape=(3, 4))
print(x)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [3]:
x = tf.zeros(shape=(2, 3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


**Random tensors**

In [5]:
x = tf.random.normal(shape=(2, 3), mean=0., stddev=1.)
print(x)

tf.Tensor(
[[-0.05700056 -0.5418321  -0.3554174 ]
 [ 0.3199175   1.5811232   0.8060244 ]], shape=(2, 3), dtype=float32)


In [6]:
x = tf.random.uniform(shape=(2, 3), minval=0., maxval=1.)
print(x)

tf.Tensor(
[[0.15887558 0.9711219  0.21631646]
 [0.37778473 0.6012497  0.37376845]], shape=(2, 3), dtype=float32)


Numpy arrays와 TensorFlow tensors 사이의 가장 큰 차이는 numpy array는 값 할당이 가능하지만 tensorflow tensor는 값 할당을 할 수 없음

**Numpy arrays are asignable**

In [9]:
import numpy as np
x = np.ones(shape=(2, 3))
print(x)
x[0, 0] = 0.
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 1. 1.]
 [1. 1. 1.]]


**TensorFlow tensors are not asignable**

In [11]:
x = tf.ones(shape=(2, 3))
print(x)
x[0, 0] = 0

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

**Creating a TensorFlow variable**

In [13]:
v = tf.Variable(initial_value=tf.random.normal(shape=(2, 3)))
print(v)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[-1.5257925 ,  0.15980071,  0.943152  ],
       [-2.47149   , -0.7109677 , -0.1946231 ]], dtype=float32)>


variale의 상태는 assign 메소드를 사용해서 변경할 수 있음

In [15]:
v.assign(tf.ones(shape=(2, 3)))
print(v)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>


**Assigning a value to a subset of a TensorFlow variable**

In [16]:
v[0, 0].assign(3.)
print(v)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[3., 1., 1.],
       [1., 1., 1.]], dtype=float32)>


```assign_add(), assign_sub()``` 는 각각 ```+=, -=```와 동일한 연산 수행

In [17]:
v.assign_add(tf.ones(shape=(2, 3)))
print(v)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[4., 2., 2.],
       [2., 2., 2.]], dtype=float32)>


### 3.5.2 Tensor operations: Doing math in TensorFlow

Numpy와 마찬가지로 TensorFlow도 다양한 수식을 표현하기 위한 다양한 텐서 연산자를 제공

**A few basic math operations**

In [18]:
a = tf.ones((2, 2))
b = tf.square(a)
c = tf.sqrt(a)
d = b + c
e = tf.matmul(a, b)
e *= d

TensorFlow도 Numpy와 마찬가지로 실행 시점에 바로 결과를 확인할 수 있음(eager execution이라고 함)